# Docker Compose
version: '3.3'

# Define services
services:
  # spring service
  app:
    image: triauddata2025:v1
    ports:
      - "8383:8082"
    container_name: triaud_amsdata_2025_cont
    depends_on:
      - db
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbams2024?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sip
      SPRING_DATASOURCE_PASSWORD: sip-ac2024
    networks:
      - triaud_net

  # Database Service (Mysql)
  db:
    image: mysql:latest
    container_name: mysql_triaud_cont
    volumes:
      - triaud_db_ams_vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: dbams2024
      MYSQL_USER: sip
      MYSQL_PASSWORD: sip-ac2024
      MYSQL_ROOT_PASSWORD: root
    networks:
      - triaud_net

  # phpmyadmin Service
  phpmyadmin:
    image: phpmyadmin
    container_name: pmadmin_triaud_cont
    depends_on:
      - db
    restart: always
    ports:
      - 8391:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - triaud_net

# Dec
volumes:
  triaud_db_ams_vol:

networks:
  triaud_net:


